// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cwdmap.Models;

namespace cwdmap.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cwdmap.Models.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("LAT")
                        .IsRequired();

                    b.Property<string>("LNG")
                        .IsRequired();

                    b.Property<string>("ProcessorAddress")
                        .IsRequired();

                    b.Property<string>("ProcessorCity")
                        .IsRequired();

                    b.Property<string>("ProcessorCounty")
                        .IsRequired();

                    b.Property<string>("ProcessorHours")
                        .IsRequired();

                    b.Property<string>("ProcessorName")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ProcessorId");

                    b.ToTable("Processors");
                });
#pragma warning restore 612, 618
        }
    }
}
